import type { Registry } from "prom-client";
import type { Express } from "express";
import { createApp } from "./application/createApp";
import { GetMammographySecondOpinionCaseUseCase } from "./application/usecases/GetMammographySecondOpinionCaseUseCase";
import { GenerateMammographySecondOpinionUseCase } from "./application/usecases/GenerateMammographySecondOpinionUseCase";
import { standaloneManifest, type StandaloneManifest } from "./domain/manifest";
import { createStructuredLogger, type StructuredLogger } from "./logging";
import { createMonitoring } from "./monitoring";
import { FileBasedMammographySecondOpinionCaseRepository } from "./infrastructure/persistence/FileBasedMammographySecondOpinionCaseRepository";
import { MammographySecondOpinionCase } from "./domain/mammography/MammographySecondOpinionCase";
import type {
  IMammographyDraftInferenceService,
  IMammographySafetyPolicy,
  IMammographySecondOpinionCaseRepository,
} from "./domain/mammography/ports";

export interface BootstrapOptions {
  metricsEnabled?: boolean;
  isShuttingDown?: () => boolean;
  logger?: StructuredLogger;
  startedAt?: Date;
  caseStorePath?: string;
}

export interface BootstrapResult {
  app: Express;
  manifest: StandaloneManifest;
  metricsRegistry: Registry;
}

export function bootstrap(options: BootstrapOptions = {}): BootstrapResult {
  const { metricsRegistry, requestCounter } = createMonitoring();
  const logger = options.logger ?? createStructuredLogger();
  const startedAt = options.startedAt ?? new Date();

  const repository = createCaseRepository(options.caseStorePath);
  const inferenceService = createBaselineInferenceService();
  const safetyPolicy = createBaselineSafetyPolicy();
  const generateCaseUseCase = new GenerateMammographySecondOpinionUseCase(
    repository,
    inferenceService,
    safetyPolicy,
  );
  const getCaseUseCase = new GetMammographySecondOpinionCaseUseCase(repository);

  const app = createApp({
    metricsEnabled: options.metricsEnabled ?? true,
    metricsRegistry,
    requestCounter,
    startedAt,
    logger,
    isShuttingDown: options.isShuttingDown ?? (() => false),
    generateCase: (input) => generateCaseUseCase.execute(input),
    getCaseById: (caseId) => getCaseUseCase.execute(caseId),
  });

  return {
    app,
    manifest: standaloneManifest,
    metricsRegistry,
  };
}

function createCaseRepository(caseStorePath?: string): IMammographySecondOpinionCaseRepository {
  if (caseStorePath) {
    return new FileBasedMammographySecondOpinionCaseRepository(caseStorePath);
  }

  return createInMemoryRepository();
}

function createInMemoryRepository(): IMammographySecondOpinionCaseRepository {
  const records = new Map<string, ReturnType<MammographySecondOpinionCase["toSnapshot"]>>();

  return {
    async save(caseAggregate) {
      records.set(caseAggregate.caseId, caseAggregate.toSnapshot());
    },

    async getById(caseId) {
      const snapshot = records.get(caseId);
      return snapshot ? MammographySecondOpinionCase.rehydrate(snapshot) : null;
    },
  };
}

function createBaselineInferenceService(): IMammographyDraftInferenceService {
  return {
    async generateDraft(exam, clinicalQuestion) {
      const densityText = exam.breastDensity ? ` Density category ${exam.breastDensity}.` : "";

      return {
        assessment: {
          summary: `Baseline draft for FFDM case: ${clinicalQuestion.questionText}${densityText}`,
          biradsCategory: "0",
          confidenceBand: "moderate",
          outputMode: "draft-only",
          findings: [
            "Four standard FFDM views are present for clinician review.",
            "Draft generated by baseline rule engine and must not bypass radiologist interpretation.",
          ],
          recommendations: [
            "Radiologist review is required before finalization.",
          ],
        },
        modelId: "baseline-rule-engine:v0",
        latencyMs: 0,
      };
    },
  };
}

function createBaselineSafetyPolicy(): IMammographySafetyPolicy {
  return {
    async evaluate(_assessment, exam) {
      const flags = [];

      if (!exam.accessionNumber) {
        flags.push({
          code: "MISSING_ACCESSION_NUMBER",
          severity: "info" as const,
          description: "Accession number is absent; downstream archive correlation may require manual confirmation.",
          blocksReview: false,
        });
      }

      return { flags };
    },
  };
}